export const colors = {
  primary: "#4da36a",
  primaryDark: "#3D441E",
  secondary: "#FFFFFF",
  secondaryDark: "#CBD5C0",
  border: "#DFE6DA",
  borderDark: "#CBD5C0",
  text: "#000000",
  placeholder: "#CBD5C0",
  gray: "gray",
  darkGray: "#282828",
  danger: "#dd0000",
  dangerSoft: "#e6004d",
  dangerDark: "#bb0000",
  primaryHover: "#3D441E",
  white: "#FFFFFF",
  black: "#1a1a1a",
  focusGreen: "#a3ccbe",
  focusPurple: "#8c5ce6",
  secondaryGray: "#DFE6DA",
  boxPlaceholderFG: "#CBD5C0",
  boxPlaceholderBG: "#DFE6DA",
} as const;
