name: Test and deployment

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"

  deploy-development:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    timeout-minutes: 30
    environment:
      name: development
    permissions:
      id-token: write
    env:
      BRANCH: ${{ github.ref }}
      OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: checkou
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: cache cdk node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: cdk/node_modules
          key: node-${{ runner.os }}-${{ hashFiles('cdk/package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: setup node_modules for cdk
        working-directory: cdk
        run: npm ci

      - name: setup node_modules
        run: npm ci

      - name: lint
        run: npm run lint

      - name: setup Next.js .env
        run: bash fetch_next_env.sh dev

      - name: deploy
        working-directory: cdk
        run: npm run deploy

      - name: slack_notify
        uses: ./.github/actions/slack_notify
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          STATUS: ${{ job.status }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.ref == 'refs/heads/main' }}
    timeout-minutes: 30
    environment:
      name: production
    permissions:
      id-token: write
    env:
      BRANCH: ${{ github.ref }}
      OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: checkou
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: cache cdk node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: cdk/node_modules
          key: node-${{ runner.os }}-${{ hashFiles('cdk/package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: setup node_modules
        working-directory: cdk
        run: npm ci

      - name: setup Next.js .env
        run: bash fetch_next_env.sh prod

      - name: deploy
        working-directory: cdk
        run: npm run deploy:prod

      - name: slack_notify
        if: success() || failure()
        uses: ./.github/actions/slack_notify
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          STATUS: ${{ job.status }}
